### ISSUE TITLE
Keycloak Discord idP - Blazor Wasm

### ISSUE THREAD

**Issue by Alexr03** [Herdo/keycloak-remember-me-authenticator#6]
Heya, sorry I don't know any other way to contact you! 🥹

I saw your post on https://stackoverflow.com/a/76357231/6622349 regarding using Keycloak and Discord as the idP and passing the prompt parameter "none" will cause the discord iframe to load, but never appear because they disallow it.

Im wondering if you found a workaround for this issue that will still allow `prompt=none` so the user does not have to authorize everytime with the same scopes.

Again, sorry i've asked this question here 😅

Thanks!

**Comment by Herdo** [comment]
@Alexr03 Hey there, the `prompt=none` part of it works. The described issue only affects the 10 seconds delay before getting redirected to the Discord page.

As of switching to .NET 8 recently and back to Cookie based auth, the issue is even less present. Only when the long lasting refresh token of Keycloak expires, then a redirect to Discord is required.
